name: Comparison Action
description: Compare your branches using Oxygen Scripting
branding:
  icon: 'git-branch'
  color: 'blue'
inputs:
  firstBranchName:
    description: 'First branch name.'
    default: 'main'
    required: true
  secondBranchName:
    description: 'Second branch name.'
    default: 'main'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout main repo with entire history.
      uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
    - name: Checkout Comparison Template repo.
      uses: actions/checkout@v3.3.0
      with:
        repository: FloriNNic/comparison-template
        path: scripting

    - name: Checkout first branch.
      uses: actions/checkout@v3.3.0
      with:
        ref: ${{ inputs.firstBranchName }}
        path: ${{ inputs.firstBranchName }}

    - name: Checkout second branch.
      uses: actions/checkout@v3.3.0
      with:
        ref: ${{ inputs.secondBranchName }}
        path: ${{ inputs.secondBranchName }}

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x ./scripting/build/gradlew
      shell: bash

    - name: Build with Gradle
      run: |
        cd scripting/build; ./gradlew runComparison -PfirstBranch=${{ inputs.firstBranchName }} -PsecondBranch=${{ inputs.secondBranchName }} --info --stacktrace --build-cache
      shell: bash

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        folder: scripting/report

